# Generated by Django 3.2 on 2021-05-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='category',
            field=models.SmallIntegerField(choices=[('İnşaat işleri', ((16, 'Kazı-dolgu'), (11, 'Kaba beton'), (12, 'Mimari işler'), (13, 'Fore Kazık'), (14, 'Dikey sondaj '), (15, 'Yatay sondaj'), (18, 'Enjeksiyon işleri'), (18, 'Kazık işleri'), (18, 'Kırma-eleme işleri'))), ('Metal işleri', ((21, 'Kalıp imalat'), (22, 'Çelik konstrüksiyon'))), ('Mekanik sistem', ((31, 'Groceries'), (32, 'Restaurants'))), ('Elektrik sistem', ((41, 'Groceries'), (52, 'Restaurants'))), ('ISG işleri', ((61, 'OSGB'), (62, 'Yüksekte imalat (iple erşim, güvanlik ağı vs'))), ('Mal ', ((61, 'OSGB'), (62, 'Yüksekte imalat (iple erşim, güvanlik ağı vs'))), ('Filo', ((10, 'Araç Filo'),))]),
        ),
    ]
