# Generated by Django 3.2 on 2021-05-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_alter_firm_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(verbose_name='Eklenme Tarihi')),
                ('firm_name', models.ManyToManyField(to='base.Subsidiary', verbose_name='Firm Name')),
            ],
        ),
    ]
