# Generated by Django 3.2 on 2021-04-25 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.SmallIntegerField(choices=[('İnşaat işleri', ((16, 'Kazı-dolgu'), (11, 'Kaba beton'), (12, 'Mimari işler'), (13, 'Fore Kazık'), (14, 'Dikey sondaj '), (15, 'Yatay sondaj'), (18, 'Enjeksiyon işleri'), (18, 'Kazık işleri'), (18, 'Kırma-eleme işleri'))), ('Metal işleri', ((21, 'Kalıp imalat'), (22, 'Çelik konstrüksiyon'))), ('Mekanik sistem', ((31, 'Groceries'), (32, 'Restaurants'))), ('Elektrik sistem', ((41, 'Groceries'), (52, 'Restaurants'))), ('ISG işleri', ((61, 'OSGB'), (62, 'Yüksekte imalat (iple erşim, güvanlik ağı vs'))), ('Mal ', ((61, 'OSGB'), (62, 'Yüksekte imalat (iple erşim, güvanlik ağı vs')))])),
            ],
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('firm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.firm')),
                ('axcode', models.CharField(max_length=3)),
            ],
            bases=('base.firm',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subsidiary')),
            ],
        ),
    ]
